import { createElement } from 'lwc';
import PropertyEditor_ObjectConfiguration from 'c/propertyEditor_ObjectConfiguration';

describe('c-property-editor-object-configuration', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-property-editor-object-configuration', {
            is: PropertyEditor_ObjectConfiguration
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});